nand: arasan_nfc: Add missing of.h
For !CONFIG_OF_MTD case of.h is missing.
Kbuild system reports error:
drivers/mtd/nand/arasan_nfc.c: In function 'anfc_probe':
drivers/mtd/nand/arasan_nfc.c:794:2: error: implicit declaration of
function 'of_property_read_bool'
[-Werror=implicit-function-declaration]
   nfc->dma = of_property_read_bool(pdev->dev.of_node,

Signed-off-by: Michal Simek <michal.simek@xilinx.com>
(cherry picked from commit 25f1e9bb657c0be538b85d6175cd74a313e1b3a2
 pulled from Xilinx' branch at https://github.com/Xilinx/linux-xlnx)

Change-Id: I574aa7c6b81e885be1805345e23f98f70c1a5aef